// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package accesstokenpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AccessTokenClient is the client API for AccessToken service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessTokenClient interface {
	Get(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error)
	Store(ctx context.Context, in *StoreAccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error)
	Delete(ctx context.Context, in *DeleteAccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error)
	Update(ctx context.Context, in *UpdateAccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error)
}

type accessTokenClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessTokenClient(cc grpc.ClientConnInterface) AccessTokenClient {
	return &accessTokenClient{cc}
}

func (c *accessTokenClient) Get(ctx context.Context, in *GetAccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, "/accesstokenpb.AccessToken/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessTokenClient) Store(ctx context.Context, in *StoreAccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, "/accesstokenpb.AccessToken/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessTokenClient) Delete(ctx context.Context, in *DeleteAccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, "/accesstokenpb.AccessToken/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessTokenClient) Update(ctx context.Context, in *UpdateAccessTokenRequest, opts ...grpc.CallOption) (*AccessTokenResponse, error) {
	out := new(AccessTokenResponse)
	err := c.cc.Invoke(ctx, "/accesstokenpb.AccessToken/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessTokenServer is the server API for AccessToken service.
// All implementations must embed UnimplementedAccessTokenServer
// for forward compatibility
type AccessTokenServer interface {
	Get(context.Context, *GetAccessTokenRequest) (*AccessTokenResponse, error)
	Store(context.Context, *StoreAccessTokenRequest) (*AccessTokenResponse, error)
	Delete(context.Context, *DeleteAccessTokenRequest) (*AccessTokenResponse, error)
	Update(context.Context, *UpdateAccessTokenRequest) (*AccessTokenResponse, error)
}

// UnimplementedAccessTokenServer must be embedded to have forward compatible implementations.
type UnimplementedAccessTokenServer struct {
}

func (UnimplementedAccessTokenServer) Get(context.Context, *GetAccessTokenRequest) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAccessTokenServer) Store(context.Context, *StoreAccessTokenRequest) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedAccessTokenServer) Delete(context.Context, *DeleteAccessTokenRequest) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAccessTokenServer) Update(context.Context, *UpdateAccessTokenRequest) (*AccessTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAccessTokenServer) mustEmbedUnimplementedAccessTokenServer() {}

// UnsafeAccessTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessTokenServer will
// result in compilation errors.
type UnsafeAccessTokenServer interface {
	mustEmbedUnimplementedAccessTokenServer()
}

func RegisterAccessTokenServer(s *grpc.Server, srv AccessTokenServer) {
	s.RegisterService(&_AccessToken_serviceDesc, srv)
}

func _AccessToken_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessTokenServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accesstokenpb.AccessToken/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessTokenServer).Get(ctx, req.(*GetAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessToken_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessTokenServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accesstokenpb.AccessToken/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessTokenServer).Store(ctx, req.(*StoreAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessToken_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessTokenServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accesstokenpb.AccessToken/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessTokenServer).Delete(ctx, req.(*DeleteAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessToken_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessTokenServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accesstokenpb.AccessToken/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessTokenServer).Update(ctx, req.(*UpdateAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccessToken_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accesstokenpb.AccessToken",
	HandlerType: (*AccessTokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _AccessToken_Get_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _AccessToken_Store_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccessToken_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccessToken_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "databases/protos/accesstokenpb/accesstokenpb.proto",
}
